### ISSUE TITLE
GT-Examples-Roassal2 should not be packaged in GT-Examples

### ISSUE THREAD

**Issue by jecisc** [moosetechnology/Moose#1180]
Because we can use GT without Roassal.

**Comment by klaranosan** [comment]
Hi

GT-Examples and GT-Examples-Roassal2 are not loaded in Moose 6.1. So the bug entry should be closed.

The openDev team.

**Comment by bergel** [comment]
Why this? GT-Examples is not part of Moose anymore? So, this means we should also remove it from Roassal. Can you provide a bit of context.

**Comment by Ducasse** [comment]
Alex 
I do not know. Now keeping obsolete bug entry is not good. 
What we checked is that in Pharo 6.1 GT-Example is not loaded. 
Then I do not understand why Roassal  should be packaged inside GTExample. 

BTW: One of these days you should take the time to realise that having multiple packages is NOT complex to manage. Because I do not understand why we have Roassal VW in Moose. I manage all my projects with dependencies and it works and it is simple to do. With git this is even simpler. 

Stef

**Comment by girba** [comment]
I believe there is a confusion here.

GT-Examples-Roassal2 was a package in the first version of GT-Examples (the one that relied on pragma dependencies) to provide extensions in the inspector for visualizing GT-Examples. In the new GTExamples, we now have GToolkit-Examples-Roassal2UI. However, one can load only the engine of examples without this package. In the case of Moose, given that Roassal is available anyway, we load it.
