### ISSUE TITLE
RTLegendBuilder onDemand doesn't popup in html

### ISSUE THREAD

**Issue by bergel** [moosetechnology/Moose#1292]
Just wanted to report that when I add a legend to RTView, it works as expected when I ispect the view.
When I export it to HTML, it shows the node, but neither mouse clicking nor hovering bring up the popup.

**Comment by akevalion** [comment]
I have updated roassal in order to use events in fixed shapes for roassal2 Please try with the next piece of code

```Smalltalk
	|  lb b |
	b := RTMondrian new.
	b shape rectangle
		width: [ :c | c numberOfVariables * 5 ];
		height: #numberOfMethods.
	b nodes: RTShape withAllSubclasses.
	b edges connectFrom: #superclass.
	b layout tree.
	b normalizer
		normalizeColor: #numberOfLinesOfCode using: (Array with: Color black with: Color red).
	b build.

	lb := RTLegendBuilder new.
	lb onDemand: '+Info'.
	lb view: b view.

	lb addText: 'System complexity view'.
	lb addRectanglePolymetricWidth: 'number of methods' height: 'Line of code' box: 'a Pharo class'.
	lb build.

	^ b view
```

The html result should be like this
<img width="609" alt="captura de pantalla 2018-04-12 a la s 05 12 11" src="https://user-images.githubusercontent.com/10532890/38664497-2c020daa-3e10-11e8-95a0-21699bf94c01.png">

**Comment by bergel** [comment]
Works well! Thanks!
