### ISSUE TITLE
Moose-Tests-Core depends on Glamour

### ISSUE THREAD

**Issue by jecisc** [moosetechnology/Moose#1367]

**Comment by pavel-krivanek** [comment]
there is one more related issue in the method `MooseEntityTest>>#testMooseFinderNavigationIn`

If you try to inspect the tested block `MooseEntity new mooseFinderNavigationIn: GLMCompositePresentation new`, you will get an error.
That's because the MooseEntity does not know its meta-model. The `FAMIXEntity` should be used here but that would add a next dependency

**Comment by pavel-krivanek** [comment]
I think that the best way will be to just remove this smoke test.

**Comment by pavel-krivanek** [comment]
fixed in https://github.com/moosetechnology/Moose/pull/1369
