### ISSUE TITLE
Not loaded packages

### ISSUE THREAD

**Issue by jecisc** [moosetechnology/Moose#1523]
In Moose we currently have not loaded packages. Maybe they should be loaded or removed.

**Comment by badetitou** [comment]
Moose-MenuBar includes code to add an entry in the Moose Menu Item to load moosetechnology project (as SmaCC or Petit Parser or FAST ...)
But I think it needs improvement

I don't know what StateSpecs-GTTools is.

**Comment by jecisc** [comment]
@badetitou When you created Famix-Group-Tests you did not add it to the baseline.

**Comment by jecisc** [comment]
Weird, I see it in the baseline but it was not loaded in my image.

**Comment by badetitou** [comment]
Is it in the groups?

**Comment by jecisc** [comment]
Seems like no. 

But by default it loads everything no?

**Comment by badetitou** [comment]
No because the group default is overwriting at the end of the methods 
`BaselineOfMoose>>#groups:`

**Comment by jecisc** [comment]
I fixed it for this package.

**Comment by badetitou** [comment]
About Ghost

The packages not loaded are Learning and Learning-Tests.

Ghost is loaded because it is a dependency of Mocketry.
And Mocketry does not need Learning.

Should we let the Learning package unload or add ghost in another place.
(we must not add learning as a dependency IMO because it does not make sense to add a dependency only because we want to load a package)

**Comment by jecisc** [comment]
Remove Learning from Moose IMO.
