### ISSUE TITLE
Add a method to reset the cache

### ISSUE THREAD

**Issue by badetitou** [moosetechnology/Moose#1602]
We do not have a method that reset all the cache (in a moosemodel).
But, it is super important

**Comment by jecisc** [comment]
You can check what I have in my scripts:
https://github.com/jecisc/pharo-scripts/blob/master/settings/PharoSettings.package/PharoQuickAccess.class/instance/flushAll.st
https://github.com/jecisc/pharo-scripts/blob/master/settings/PharoSettings.package/PharoQuickAccess.class/instance/flushGroups.st
https://github.com/jecisc/pharo-scripts/blob/master/settings/PharoSettings.package/PharoQuickAccess.class/instance/flushProperties.st

This is code I had in Moose 6.1

**Comment by badetitou** [comment]
I got a question about your script.
Are we sure that the privateState contains only cached information?

**Comment by jecisc** [comment]
It does not but #flush will flush only the caches. (Except if you don't use it well).

At least in Moose 6.1:
```Smalltalk
flush  
	self flushProperties. 
	self flushGroups
```

**Comment by jecisc** [comment]
A MooseState has three concepts:
- Attributes: Those should be the information that cannot be computed (such as the protocol of a method)
- Properties: Those are the cache of properties. For example when you ask to compute the number of methods of a class
- Groups: Those are only used for bookmarks, for now, I have the impression. Maybe we could remove it? 

Also, there is something you should now. We currently have different kinds of private state. The main two are a Development private state and the Memory efficient private state. The first one will have groups and properties in two different dictionaries. The second is the default and will keep both in the same dictionary (So flushGroup = flushProperties). It's like this because adding a dictionary to all moose entity is not memory efficient. Especially since one of them is only used by bookmarks.
