### ISSUE TITLE
Moose 8 gives warning when loading PlantUMLGizmo

### ISSUE THREAD

**Issue by fuhrmanator** [moosetechnology/Moose#2012]
When executing **Moose > Moose Projects > Load PlantUML Gizmo** in the latest Moose 8 (development version), there's a warning that pops up:

    This package depends on the following classes:
      ZnUrlTests
    You must resolve these dependencies before you will be able to load these definitions: 
      ZnUrlTests>>#testIsValid

![image](https://user-images.githubusercontent.com/7606540/67642002-b6cf2380-f8dd-11e9-85d9-66fa3a0923f5.png)

Is it a problem in the PlantUML Gizmo baseline (missing dependency) or how it's loaded in Moose?

It's not a major problem, but I would like to avoid the warning when I do tutorials with students who are new to Moose.

**Comment by jecisc** [comment]
@fuhrmanator In Pharo 8 I renamed this class ZnUrlTest instead of ZnUrlTests. 

I see two possible solutions to your problem.

You are probably adding a test as an extension to this class. If you do not use a set from this class directly, I would recommend you to put the test in one of your own test cases.
If you are using a setup from this class, I would recommend you to add a class named `ZnUrlTests` as a subclass of ZnUrlTest in a package that will be loaded only in Pharo 8.

**Comment by jecisc** [comment]
If you don't know how to do it, I can help you.

**Comment by fuhrmanator** [comment]
I understand how to do it, although it is complex. 

The root of the problem is that `ZnUrl` has no `isValid` method (which I realize is ambitious to do perfectly). The extension in `PUGizmo` provides an implementation (albeit a regex validation). I also wrote some basic tests, which is where the renaming caused the problem.

The ultimate solution would be to have those extensions be added to `ZnUrl` and its test class (at least in P8). Is it worth pursuing it as a PR to those? I'd rather spend my energy there (for the community) than just a complex fix in PUGizmo only.

**Comment by badetitou** [comment]
see: https://github.com/fuhrmanator/PlantUMLPharoGizmo/pull/12

**Comment by badetitou** [comment]
done
