### ISSUE TITLE
what is the use of FamixTHasImmediateSource>>isFile ?

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/Moose#2122]
#isFile is a pharo selector that is not implemented elsewhere in Famix

**Comment by anneetien** [comment]
It is also defined in FamixTFileAnchor. 
So should we remove it?

**Comment by mahugnon** [comment]
I think it makes sense to keep it in Moose or maybe rename it if you like because it is used to check it an Anchor is File base or not. For instance  `FAMIXPharoFileAnchor>> isFile[^false]`  where  `FAMIXFileAnchor>>isFile[^true]`

**Comment by jecisc** [comment]
While migrating the duplication algorithm I added #isFileAnchor to FamixTSourceAnchor and to FamixTFileAnchor. 

On top of that, I updated the FamixGenerator so that *all* source anchors use FmaixTSourceAnchor. 

Thus, I propose to deprecate #isFile in favor of #isFileAnchor and remove all the methods from the concrete classes.

**Comment by jecisc** [comment]
Related to https://github.com/moosetechnology/Moose/issues/1205

**Comment by jecisc** [comment]
I made a PR
