### ISSUE TITLE
Moose 10 template includes wrong Pharo version

### ISSUE THREAD

**Issue by Bajger** [moosetechnology/Moose#2494]
This is follow-up to issue: https://github.com/pharo-project/pharo-launcher/issues/615

Problem occurs when Moose image is downloaded and launched in Pharo launcher: 
![image](https://github.com/moosetechnology/Moose/assets/45875448/0e68b6c2-2b3a-420d-a106-7ee1b7b9e9ed)

This is because pharo.version file that is part of zip archive includes "10" but it should be "100" (as for other P10 template images - see content of pharo.version of official P10 stable version template).

Development effort:
fix content of pharo.version file and prepare new zip.

**Comment by Bajger** [comment]
I guess related code for producing pharo.version is here in PhLVirtualMachineManager>>imageVersionDeterminationScript: 
![image](https://github.com/moosetechnology/Moose/assets/45875448/ce9b609d-4500-4e0a-aa70-0bfd8971035b)

**Comment by Bajger** [comment]
@ClotildeToullec Or maybe this commit? https://github.com/moosetechnology/Moose/commit/d1d9f1acb14358cad3a4998ba4a61eb1cf61aa0a

**Comment by ClotildeToullec** [comment]
Hello, I'm currently fixing this. 

> @ClotildeToullec Or maybe this commit? [d1d9f1a](https://github.com/moosetechnology/Moose/commit/d1d9f1acb14358cad3a4998ba4a61eb1cf61aa0a)

This commit is actually supposed to fix it, but the CI fails for an unrelated reason that I'm working on now. When it works, the correct version file will be generated.

**Comment by ClotildeToullec** [comment]
Fixed now

**Comment by fuhrmanator** [comment]
Yesterday, when I started Pharo Launcher 3.0.1 on Windows, I was prompted to update templates (I said yes). As far as I know, this is when this problem started for me.

Can anyone say how PL determines if there are template updates and where they're downloaded from?

**Comment by ClotildeToullec** [comment]
The problem should be fixed now.

The update message in the pharo launcher happens when the `source.list` file on your computer is not up to date with the source file online (https://files.pharo.org/pharo-launcher/).

The error in Moose 10 version is mine and not from Pharo Launcher. We generate a `pharo.version` file in Moose when we update the release. I used the script that worked until Pharo 9 instead of the one working with 2 digits Pharo versions.

The fact that you saw the change after an update in the pharo launcher is not directly but indirectly related: I managed Moose releases and did a PR to the Pharo Launcher for Moose sources the same day.

The Moose 10 image downloaded in the Pharo Launcher is in the assets here: https://github.com/moosetechnology/Moose/releases/tag/v10.x.x .
The development version, updated every day is here: https://github.com/moosetechnology/Moose/releases/tag/continuous

**Comment by ClotildeToullec** [comment]
I fixed the script and generated a fresh Moose 10 image, so now you should be able to download and launch a Moose 10 image from the Pharo launcher.
Pharo launcher will not inform you, as the new version is at the same url as before.

**Comment by fuhrmanator** [comment]
Thanks @ClotildeToullec -- I just tried it with updated scripts and it's OK.
